NAMES = ["John", "Paul", "George", "Ringo"]
AGES = [20, 21, 22, 23]

JOHN = NAMES[0]
PAUL = NAMES[1]

JOHN_PAUL = NAMES[:2]
JOHN_PAUL_GEORGE = NAMES[:3]
JOHN_PAUL_GEORGE_RINGO = NAMES[:]
GEORGE_RINGO = NAMES[2:]
REVERSE = NAMES[::-1]
EVERY_OTHER = NAMES[::2]

print(sum(AGES))
print(min(AGES))
print(max(AGES))

print(JOHN_PAUL)
print(JOHN_PAUL_GEORGE)
print(JOHN_PAUL_GEORGE_RINGO)
print(GEORGE_RINGO)
print(REVERSE)
